name:                space-invaders
version:             0.1.0.0
description:         Emulator for Space Invaders, running on Intel 8080
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              https://github.com/Nick-Chapman/space-invaders.git

extra-source-files:
- README.md

dependencies:
- array
- base >= 4.7 && < 5
- containers
- ansi-terminal
- haskeline
- mtl
- time
- transformers

default-extensions:
- BangPatterns
- DuplicateRecordFields
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- ScopedTypeVariables
- TypeApplications

- TypeFamilies
#- DatatypeContexts
#- UndecidableInstances
#- AllowAmbiguousTypes


ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        space-invaders
